
name: fitforge_onboarding_professional
description: A professional gym app with onboarding screens.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^3.1.2


flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/lottie/fitness.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
