// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcYZUY9TJLp3d_wz433Nh8H7zcWc6Q4Y',
    appId: '1:974294476008:web:ddf87ba2bbdb1d2231d55d',
    messagingSenderId: '974294476008',
    projectId: 'fitforge-3a05e',
    authDomain: 'fitforge-3a05e.firebaseapp.com',
    storageBucket: 'fitforge-3a05e.firebasestorage.app',
    measurementId: 'G-RM1MZKTFZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzi5tIxRCMYuXGAhpn-26j0ijtmsVvfdE',
    appId: '1:974294476008:android:1ff11cb8a79103dc31d55d',
    messagingSenderId: '974294476008',
    projectId: 'fitforge-3a05e',
    storageBucket: 'fitforge-3a05e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4CW3SPB9Iqz46qcWyO8gwdz0ehVc_1J8',
    appId: '1:974294476008:ios:0ed090f0352b9b4831d55d',
    messagingSenderId: '974294476008',
    projectId: 'fitforge-3a05e',
    storageBucket: 'fitforge-3a05e.firebasestorage.app',
    iosBundleId: 'com.example.fitforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4CW3SPB9Iqz46qcWyO8gwdz0ehVc_1J8',
    appId: '1:974294476008:ios:0ed090f0352b9b4831d55d',
    messagingSenderId: '974294476008',
    projectId: 'fitforge-3a05e',
    storageBucket: 'fitforge-3a05e.firebasestorage.app',
    iosBundleId: 'com.example.fitforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIcYZUY9TJLp3d_wz433Nh8H7zcWc6Q4Y',
    appId: '1:974294476008:web:2a09a36a16188a3731d55d',
    messagingSenderId: '974294476008',
    projectId: 'fitforge-3a05e',
    authDomain: 'fitforge-3a05e.firebaseapp.com',
    storageBucket: 'fitforge-3a05e.firebasestorage.app',
    measurementId: 'G-C2CET0LQ9Y',
  );

}